"""empty message

Revision ID: d81b809d39d5
Revises: 
Create Date: 2020-10-07 14:27:03.112107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd81b809d39d5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persontasks', sa.Column('dueby', sa.DateTime(), nullable=False))
    op.add_column('persontasks', sa.Column('personid', sa.Integer(), nullable=False))
    op.add_column('persontasks', sa.Column('startdate', sa.DateTime(), nullable=False))
    op.add_column('persontasks', sa.Column('taskid', sa.Integer(), nullable=False))
    op.drop_constraint('fk_person_task_person', 'persontasks', type_='foreignkey')
    op.drop_constraint('fk_person_task_task', 'persontasks', type_='foreignkey')
    op.create_foreign_key('fk_person_task_task', 'persontasks', 'task', ['taskid'], ['id'])
    op.create_foreign_key('fk_person_task_person', 'persontasks', 'person', ['personid'], ['id'])
    op.drop_column('persontasks', 'taskId')
    op.drop_column('persontasks', 'startDate')
    op.drop_column('persontasks', 'personId')
    op.drop_column('persontasks', 'dueBy')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persontasks', sa.Column('dueBy', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('persontasks', sa.Column('personId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('persontasks', sa.Column('startDate', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('persontasks', sa.Column('taskId', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_person_task_person', 'persontasks', type_='foreignkey')
    op.drop_constraint('fk_person_task_task', 'persontasks', type_='foreignkey')
    op.create_foreign_key('fk_person_task_task', 'persontasks', 'task', ['taskId'], ['id'])
    op.create_foreign_key('fk_person_task_person', 'persontasks', 'person', ['personId'], ['id'])
    op.drop_column('persontasks', 'taskid')
    op.drop_column('persontasks', 'startdate')
    op.drop_column('persontasks', 'personid')
    op.drop_column('persontasks', 'dueby')
    # ### end Alembic commands ###
